#DB Properties
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: educ-grad-graduation-report-api-cp
      connection-timeout: ${CONNECTION_TIMEOUT}
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      minimum-idle: ${MIN_IDLE}
      idle-timeout: ${IDLE_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    url: ${CONNECTION_STRING}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: ${SHOW_SQL_LOGS}
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  codec:
    max-in-memory-size: 20MB
  #Keycloak/OAuth properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL}
          jwk-set-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/certs

#Logging properties
logging:
  file:
    name: /logs/app.log
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 20MB
      clean-history-on-start: true
  pattern:
    file: '{"time_stamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%3p" ,"thread":"%t" ,"class":"%logger{36}","msg":"%replace(%msg){"[\n\r\"]",""}", "exception":"%replace(%rEx{10}){"[\n\r\"]",""}","http_event":%X{httpEvent:-""},"message_event":%X{messageEvent:-""}}%nopex%n'
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%t] [%logger{36}] [%replace(%msg){'[\n\r\"]',''} %X{httpEvent} %X{messageEvent}] %replace(%rEx{10}){'[\n\r\"]',''}%nopex%n"
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              grad:
                report: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}
    com:
      zaxxer:
        hikari: ERROR

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}
  max-http-request-header-size: 20000

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

authorization:
  user: ${GRAD_CLIENT_NAME}
  password: ${GRAD_CLIENT_SECRET}
  token-expiry-offset: '30'

#Endpoint
endpoint:
  keycloak:
    getToken: ${KEYCLOAK_TOKEN_URL}auth/realms/master/protocol/openid-connect/token
  grad-student-api:
    get-students-for-yearly-run: ${GRAD_STUDENT_API}api/v1/student/yearlydistribution
    get-students-for-school-run: ${GRAD_STUDENT_API}api/v1/student/studentschoolreportdata
    student-for-special-grad-run-list: ${GRAD_STUDENT_API}api/v1/student/studentlistsearch
  grad-trax-api:
    school-by-school-id:
      url: ${GRAD_TRAX_API}api/v2/trax/school-clob/%s
    district-by-min-code:
      url: ${GRAD_TRAX_API}api/v2/trax/district?distNo=%s

#Splunk LogHelper
splunk:
  log-helper:
    enabled: ${ENABLE_SPLUNK_LOG_HELPER}
